FridgeAPP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('recipes/', include('recipes.urls')),
    path('user/', include('authentication.urls')),
    path('my/', include('fridge.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.contrib import admin
from django.urls import path

from home.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
]

recipes/urls.py
from django.contrib import admin
from django.urls import path, include

from recipes.views import RecipesListView, RecipeDetailView, recipe_detail

urlpatterns = [
    path('', RecipesListView.as_view(), name='recipes-all'),
    path('detail/<int:pk>', recipe_detail, name='recipes-detail'),

]

recipes/models.py
from django.db import models

# Create your models here.
quantity_type = (('1', 'pcs'),
                 ('2', 'grams'),
                 ('3', 'ml'))

difficulty_type = (('1', 'Easy'),
                   ('2', 'Medium'),
                   ('3', 'Experienced'))


class Ingredient(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    # type_quantity = models.CharField(max_length=20, choices=quantity_type, null=False, blank=False)

    # def get_type_quantity_display(self):
    #     return dict(quantity_type)[self.type_quantity]

    def __str__(self):
        return self.name


class RecipeModel(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    image = models.ImageField(upload_to='recipes/', null=True, blank=False)
    time = models.IntegerField(null=True, blank=False)
    difficulty = models.CharField(max_length=20, choices=difficulty_type, null=True, blank=False)
    ingredients = models.ManyToManyField(Ingredient, related_name="ingredients")

    def get_difficulty_display(self):
        return dict(difficulty_type)[self.difficulty]


    def get_recipe_steps(self):
        return self.recipesteps_set.all()

    def __str__(self):
        return f"{self.name} - id: {self.id} - {self.difficulty}"


#
# class IngredientsRecipe(models.Model):
#     ingredients = models.ForeignKey(IngredientsList, on_delete=models.CASCADE)
#     recipe = models.ForeignKey(RecipeModel, on_delete=models.CASCADE)
#     quantity = models.IntegerField(null=False, blank=False)
#     def __str__(self):
#         return f"{self.ingredients} - {self.quantity} - {self.ingredients.get_type_quantity_display()} - {self.recipe.name}"

class RecipeSteps(models.Model):
    recipe = models.ForeignKey(RecipeModel, on_delete=models.CASCADE)
    step_description = models.TextField(null=False, blank=False)

    def __str__(self):
        return f"Step for {self.recipe}"

recipes/views.py
from django.db.models import Count
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from fridge.models import FridgeIngredient
from recipes.models import *


# Create your views here.

class RecipesListView(ListView):
    template_name = "recipes/recipes_all.html"
    model = RecipeModel



class RecipeDetailView(DetailView):
    template_name = "recipes/recipe_detail.html"
    model = RecipeModel

    # def get_context_data(self, **kwargs):
    #     context = super(RecipeDetailView, self).get_context_data(**kwargs)
    #     context["stepslist"] = [{"step_description": "Step 1"}, {"step_description": "Step 2"}]
    #     return context


def recipe_detail(request, pk):
    context = {}
    recipe = RecipeModel.objects.filter(id=pk).all()
    steps = RecipeSteps.objects.filter(recipe_id=pk)
    ingredients = RecipeModel.objects.filter(id=recipe[0].id).values("ingredients__name")

    context['recipe'] = recipe
    context['steps'] = steps
    context['ingredients'] = ingredients

    #RecipeModel.objects.filter(ingredients__in=[1,2,3])
    return render(request, 'recipes/recipe_detail.html', context)


class RecipeStepsListView(ListView):
    template_name = "recipes/recipe_detail.html"
    model = RecipeSteps

    def get_context_data(self, **kwargs):
        context = super(RecipeStepsListView, self).get_context_data(**kwargs)
        context["stepslist"] = [{"step_description": "Step 1"}, {"step_description": "Step 2"}]
        return context


def index(request):
    recipes = RecipeModel.objects.all()
    steps = RecipeStepsListView.as_view()

    return render(request, "recipes/recipes_all.html", {"recipes": recipes, "steps": steps})

templates/recipes/recipe_detail.html
{% extends 'layout/base-recipes.html' %}
{% load static %}
{% block content %}



    <section id="stats" class="stats">
        <style> h3 {
            color: white
        } </style>
        <img src="{% static 'assets/img/spices-of-sri-lanka-brixlk_.jpg' %}" alt="" data-aos="fade-in">
        <div class="container position-relative" data-aos="fade-in" data-aos-delay="100">
            <div class="stats-item text-center w-100 h-100">
                {% for item in recipe %}

                <span>{{ item.name }}</span>
                                    
            
            <p>Cooking time</p>

                <h3 data-purecounter-start="0" data-purecounter-end="{{ item.time }}"
                    data-purecounter-duration="1" class="purecounter">Recipes</h3>
            {% endfor %}
                <p> Minutes</p>
            </div>
        </div>
    </section>

    <!-- Blog-details Section - Blog Details Page -->
    <section id="blog-details" class="blog-details">

        <div class="container" data-aos="fade-up" data-aos-delay="100">
            <div class="row g-5">

                <div class="col-lg-8">

                    <article class="article">

                        <div class="post-img">
                            <img src="assets/img/blog/blog-1.jpg" alt="" class="img-fluid">
                        </div>
{% for name in recipe %}
                        <h2 class="title">{{ name.name }}</h2>
                    {% endfor %}

                        <div class="meta-top">
                            <ul>
                                {% for time in recipe %}
                                <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                                        href="">{{ time.time }} Minutes</a></li>
                                {% endfor %}
                            </ul>
                        </div><!-- End meta top -->

                        <div class="content">
                        
                                {% for step in steps %}
                                    <p>{{ step.step_description }}</p>
                                {% endfor %}
                          

{% for image in recipe %}
                            <img src="{{ image.image.url }}" class="img-fluid" alt="">
                        {% endfor %}


                        </div><!-- End post content -->


                    </article><!-- End post article -->

                   

                </div>

                <div class="col-lg-4">

                    <div class="sidebar">

                        <div class="sidebar-item categories">
                            <h3 class="sidebar-title">Ingredients</h3>
                            <ul class="mt-3">
                                {% for i in ingredients %}
                                <li>{{ i.ingredients__name }}</li>
                               {% endfor %}

                            </ul>
                        </div><!-- End sidebar categories-->

                       
                      
                        </div>
                    

                    </div><!-- End Sidebar -->

                </div>

            </div>

        </div>

    </section><!-- End Blog-details Section -->

    </main>

{% endblock content %}

templates/recipes/recipes_all.html
{% extends 'layout/base-recipes.html' %}
{% load static %}
{% block content %}



    <section id="stats" class="stats">
        <style> h3 {
            color: white
        } </style>
        <img  src="{% static 'assets/img/spices-of-sri-lanka-brixlk_.jpg' %}" alt="" data-aos="fade-in">
        <div class="container position-relative" data-aos="fade-in" data-aos-delay="100">
            <div  class="stats-item text-center">
                <span>Recipes</span>
                <h3 data-purecounter-start="0" data-purecounter-end="{{ recipemodel_list.count }}"
                    data-purecounter-duration="1" class="purecounter"></h3>
                <p> Try our healthy recipes</p>
            </div>
        </div>
    </section>


    <section id="blog" class="blog">


        <div class="container" data-aos="fade-up" data-aos-delay="100">

            <div class="row gy-4 posts-list">
                {% for recipe in object_list %}
                    <div class="col-xl-4 col-lg-6">
                        <article>

                            <div class="post-img">
                                <img src="{{ recipe.image.url }}" alt="" class="img-fluid">
                            </div>

                            <p class="post-category">{{ recipe.time }} Minutes</p>

                            <h2 class="title">
                                <a href="{% url 'recipes-detail' recipe.id %}">{{ recipe.name }}</a>
                            </h2>

                            
                        </article>
                    </div><!-- End post list item -->
                {% endfor %}

            </div>
        </div>

{# <div class="pagination d-flex justify-content-center">#}
{#        <ul>#}
{#            <li  class="active" ><a href="#">1</a></li>#}
{#            <li><a href="#">2</a></li>#}
{#            <li><a href="#">3</a></li>#}
{#        </ul>#}
{#    </div><!-- End pagination -->#}
{#    </section>#}
   



{% endblock content %}